disabled_rules:
  - trailing_whitespace
  - trailing_comma
opt_in_rules:
  - empty_count
  - empty_string
included:
  - CopyPrompt
excluded:
  - Pods
  - build
  - .build
line_length:
  warning: 120
  error: 200
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
